### ISSUE TITLE
npm install vue-panzoom --save doesn't work

### ISSUE THREAD

**Issue by rob-sullivan** [mistabiggx/vue-panzoom#1]
npm install vue-panzoom --save doesn't work.

After install.  I add code in main.js and then add <panzoom> </panzoom>

I get panzoom not installed and then it tells me to npm install vue-panzoom --save it.

Is the issue similar to [this](https://stackoverflow.com/questions/47540846/dependency-not-found-even-defined-in-package-json-and-node-modules)?

**Comment by RubenSibon** [comment]
It seem so be a similar problem. In this case it should find "vue-zoom.js" in a `dist` directory, but that does not exist.

**Comment by mistabiggx** [comment]
Kindly update to the latest version. The build process has been fixed

**Comment by mistabiggx** [comment]
Has been fixed in latest version 1.1.0
