### ISSUE TITLE
Issue initializing panzoom on firefox due screenCTM

### ISSUE THREAD

**Issue by theveloped** [mistabiggx/vue-panzoom#17]
Hi, I'm still having some ittues getting panzoom to work properly on firefox browsers. It seems screenCTM returns null in some cases causing panzoom to fail. I think this is an issue with firefox (see also this issue at the svg.js: https://github.com/svgdotjs/svg.js/issues/968) it would however be nice if panzoom would work cross browser even with this firefox issue being present.

![image](https://user-images.githubusercontent.com/15847277/80961340-0baea200-8e0b-11ea-9c02-88c51aa84b6a.png)

Is there any workaround we could implement? I'd be happy to help but am at a loss as where to start on this.

**Comment by mistabiggx** [comment]
Kindly refer to the primary library https://github.com/anvaka/panzoom
